version: "2"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysqldockercontainer
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: socialmedia
  myapp:
    image: myappmaven
    depends_on: 
      - "db"
        #condition: service_healthy
    ports: 
      - "8082:8080"
    restart: always
    command: bash -c "mvn clean install"
    command: bash -c "java -jar /app/target/SocialMedia-0.0.1-SNAPSHOT.jar"
